// let circle1 = viz.append("svg")
//                     .append("circle")
//                       .attr("r", 4)
//                       .attr("fill", "lightblue")
//                       .attr("x", 100)
//                       .attr("y", 500)
// ;
// let circle2 = viz.append("svg")
//                     .append("circle")
//                       .attr("r", 4)
//                       .attr("fill", "pink")
//                       .attr("x", 100)
//                       .attr("y", 520)
// ;
// let circle3 = viz.append("svg")
//                     .append("circle")
//                       .attr("r", 4)
//                       .attr("fill", "lightgreen")
//                       .attr("x", 100)
//                       .attr("y", 540)
// ;
// let circle4 = viz.append("svg")
//                     .append("circle")
//                       .attr("r", 4)
//                       .attr("fill", "gray")
//                       .attr("x", 100)
//                       .attr("y", 560)
// ;
// let circle5 = viz.append("svg")
//                     .append("circle")
//                       .attr("r", 4)
//                       .attr("fill", "orange")
//                       .attr("x", 100)
//                       .attr("y", 580)
// ;
