let w = 1200;
let h = 800;

let viz = d3.select("#container")
                .append("svg")
                    .attr("width", w)
                    .attr("height", h)
                    // .style("fill", "black")
;

let title = viz.append("text")
                  .text("How to Read Me ...")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 50)
                  .attr("font-weight","bold")
                  .attr("fill", "black")
                  .attr("x", 80)
                  .attr("y", 100)
;
let subt1 = viz.append("text")
                  .text("* “Matrix” Graph")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 30)
                  .attr("fill", "black")
                  .attr("x", 100)
                  .attr("y", 160)
;
let expl1 = viz.append("text")
                  .text("Numbers and causes of my laughter break down into 14 days.")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 30)
                  .attr("fill", "black")
                  .attr("x", 140)
                  .attr("y", 220)
;
let subt2 = viz.append("text")
                  .text("* Area Graph")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 30)
                  .attr("fill", "black")
                  .attr("x", 100)
                  .attr("y", 280)
;
let expl2 = viz.append("text")
                  .text("Trend and cumulated totals of my laughter over 14 days.")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 30)
                  .attr("fill", "black")
                  .attr("x", 140)
                  .attr("y", 340)
;
let subt3 = viz.append("text")
                  .text("* Each color represents one cause of my laughter")
                  .attr("font-family", "Mansalva")
                  .attr("font-size", 30)
                  .attr("fill", "black")
                  .attr("x", 100)
                  .attr("y", 410)
;

let circle1 = viz.append("circle")
                      .attr("r", 10)
                      .attr("fill", "lightblue")
                      .attr("cx", 150)
                      .attr("cy", 461)
;
let text1 = viz.append("text")
                    .text("Family")
                    .attr("font-family", "Mansalva")
                    .attr("font-size", "30")
                    .attr("stroke", "lightblue")
                    .attr("x", 180)
                    .attr("y", 470)
;

let circle2 = viz.append("circle")
                  .attr("r", 10)
                  .attr("fill", "pink")
                  .attr("cx", 150)
                  .attr("cy", 521)
;
let text2 = viz.append("text")
                    .text("Friends")
                    .attr("font-family", "Mansalva")
                    .attr("font-size", "30")
                    .attr("stroke", "pink")
                    .attr("x", 180)
                    .attr("y", 530)
;
let circle3 = viz.append("circle")
                  .attr("r", 10)
                  .attr("fill", "lightgreen")
                  .attr("cx", 150)
                  .attr("cy", 581)
;
let text3 = viz.append("text")
                    .text("Professors")
                    .attr("font-family", "Mansalva")
                    .attr("font-size", "30")
                    .attr("stroke", "lightgreen")
                    .attr("x", 180)
                    .attr("y", 590)
let circle4 = viz.append("circle")
                  .attr("r", 10)
                  .attr("fill", "orange")
                  .attr("cx", 150)
                  .attr("cy", 641)
;
let text4 = viz.append("text")
                    .text("Strangers")
                    .attr("font-family", "Mansalva")
                    .attr("font-size", "30")
                    .attr("stroke", "orange")
                    .attr("x", 180)
                    .attr("y", 650)
// let circle5 = viz.append("circle")
//                   .attr("r", 10)
//                   .attr("fill", "gray")
//                   .attr("cx", 150)
//                   .attr("cy", 701)
// ;
// let text5 = viz.append("text")
//                     .text("Alone")
//                     .attr("font-family", "Mansalva")
//                     .attr("font-size", "30")
//                     .attr("stroke", "gray")
//                     .attr("x", 180)
//                     .attr("y", 710)
